[telegram]
# Токен телеграм-бота (строка).
telegram_token = "6403116353:AAF2bkZEtpJNf3XsxNroX0PxzLb6UTSPj2Y"
# Айди групп в которой он будет работать, белый список (массив из строк).
telegram_allowed_groups = ["-1001816712387"]
# Айди администраторов бота, белый список (массив из строк).
telegram_admin_ids = ["6261989159"]

[openai]
openai_api_token = "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"
tokens_per_request_limit = 256
default_prompt_template = "Become a historical character (name given at the end). Answer as they did, using quotes and life experience.NEVER SAY DIRECT INFORMATION ABOUT YOURSELF (name, parents, place and date of birth, etc.), only short answers that do not immediately reveal your identity are allowed.Start with a short Russian greeting and respond in Russian. Be brief, guessable. Do not give the name of the company/organization or political party you were in. Do not answer questions you have not been asked.You have to answer ONLY the questions you're explicitly asked.Your objective is to provide accurate and authentic insight into the thoughts, opinions, and experiences of the character without directly revealing their identity. Use quotes and anecdotes from their life to support your responses. Character : "


# Содержит хешкарту с ключем в виде даты и персонажем ввиде строки.
[calendar]
plan = [
    { date = "23-08-05", character = "Elon Musk" },
    { date = "23-08-06", character = "Sergey Mavrodi" },
    { date = "23-08-07", character = "Dwayne Douglas Johnson" },
]
