[telegram]
# Токен телеграм-бота (строка).
telegram_token = "6431499382:AAHLkiuhOh0gwQpwLcMtBw0kwW-isqrBOFg"
# Айди групп в которой он будет работать, белый список (массив из строк).
telegram_allowed_groups = ["-1001383474381", "-1001816712387"]
# Айди администраторов бота, белый список (массив из строк).
telegram_admin_ids = ["6261989159", "667588148"]

[openai]
openai_api_token = "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"
character_tokens_per_request_limit = 412
gpt_tokens_per_request_limit = 1600
default_prompt_template = "Become a historical character (name given at the end). NEVER give direct information about yourself (name, parents, place and date of birth, etc.), only short answers that do not immediately reveal your identity are allowed. Answer only in that language you have been asked. Be concise, be direct. Do not mention the name of the company/organization or political party you belong to. Do not answer questions that you have not been asked. You should answer ONLY those questions that you are explicitly asked. Your job is to give an accurate and true representation of the character's thoughts, opinions, and experiences without directly revealing their identity. Use quotes and anecdotes from their life to substantiate your answers. Character : "
helper_prompt_template = "You're in a chat room. You are trying to be as helpful as possible to the other chat participants. Respond in the language in which you are addressed."
prompt_blacklist_words = ["имя", "name", "фамилия", "surname", "фамилию"]


# Содержит хешкарту с ключем в виде даты и персонажем ввиде строки.
[calendar]
plan = [
	{ date = "23-09-16", character = ["Пётр I", "Peter the Great"] },
	{ date = "23-09-17", character = ["Джордж Вашингтон", "George Washington"] },
	{ date = "23-09-18", character = ["Иван Грозный", "Ivan the Terrible"] },
	{ date = "23-09-19", character = ["Клеопатра", "Cleopatra"] },
	{ date = "23-09-20", character = ["Франсиско Франко", "Francisco Franco Bahamonde"] },
	{ date = "23-09-21", character = ["Леонардо да Винчи", "Leonardo da Vinci"] },
	{ date = "23-09-22", character = ["Нельсон Мандела", "Nelson Mandela"] },
	{ date = "23-09-23", character = ["Жанна Д'Арк", "Joan of Arc"] },
	{ date = "23-09-24", character = ["Анна Каренина", "Anna Karenina"] },
	{ date = "23-09-25", character = ["Фрэнклин Рузвельт", "Franklin D. Roosevelt"] },
	{ date = "23-09-26", character = ["Вильгельм Шекспир", "William Shakespeare"] },
	{ date = "23-09-27", character = ["Елизавета I", "Elizabeth I"] },
	{ date = "23-09-28", character = ["Луи Армстронг", "Louis Armstrong"] },
	{ date = "23-09-29", character = ["Генри Форд", "Henry Ford"] },
]
