[telegram]
# Токен телеграм-бота (строка).
telegram_token = "6431499382:AAHLkiuhOh0gwQpwLcMtBw0kwW-isqrBOFg"
# Айди групп в которой он будет работать, белый список (массив из строк).
telegram_allowed_groups = ["-1001383474381", "-1001816712387"]
# Айди администраторов бота, белый список (массив из строк).
telegram_admin_ids = ["6261989159", "667588148"]

[openai]
openai_api_token = "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"
character_tokens_per_request_limit = 412
gpt_tokens_per_request_limit = 1600
default_prompt_template = "Become a historical character (name given at the end). NEVER give direct information about yourself (name, parents, place and date of birth, etc.), only short answers that do not immediately reveal your identity are allowed. Answer only in that language you have been asked. Be concise, be direct. Do not mention the name of the company/organization or political party you belong to. Do not answer questions that you have not been asked. You should answer ONLY those questions that you are explicitly asked. Your job is to give an accurate and true representation of the character's thoughts, opinions, and experiences without directly revealing their identity. Use quotes and anecdotes from their life to substantiate your answers. Character : "
helper_prompt_template = "You're in a chat room. You are trying to be as helpful as possible to the other chat participants. Respond in the language in which you are addressed."
prompt_blacklist_words = ["имя", "name", "фамилия", "surname", "фамилию"]


# Содержит хешкарту с ключем в виде даты и персонажем ввиде строки.
[calendar]
plan = [
	{ date = "23-09-30", character = ["Альберт Эйнштейн", "Albert Einstein"] },
	{ date = "23-10-01", character = ["Мартин Лютер Кинг", "Martin Luther King Jr."] },
	{ date = "23-10-02", character = ["Махатма Ганди", "Mahatma Gandhi"] },
	{ date = "23-10-03", character = ["Мария Кюри", "Marie Curie"] },
	{ date = "23-10-04", character = ["Чарльз Дарвин", "Charles Darwin"] },
	{ date = "23-10-05", character = ["Винсент ван Гог", "Vincent van Gogh"] },
	{ date = "23-10-06", character = ["Моцарт", "Wolfgang Amadeus Mozart"] },
	{ date = "23-10-07", character = ["Фридрих Ницше", "Friedrich Nietzsche"] },
	{ date = "23-10-08", character = ["Агата Кристи", "Agatha Christie"] },
	{ date = "23-10-09", character = ["Боб Марли", "Bob Marley"] },
	{ date = "23-10-10", character = ["Майкл Джексон", "Michael Jackson"] },
	{ date = "23-10-11", character = ["Стив Джобс", "Steve Jobs"] },
	{ date = "23-10-12", character = ["Мать Тереза", "Mother Teresa"] },
	{ date = "23-10-13", character = ["Оскар Уайльд", "Oscar Wilde"] },
	{ date = "23-10-14", character = ["Бетховен", "Ludwig van Beethoven"] },
	{ date = "23-10-15", character = ["Фрида Кало", "Frida Kahlo"] },
]
