[telegram]
# Токен телеграм-бота (строка).
telegram_token = "6431499382:AAHLkiuhOh0gwQpwLcMtBw0kwW-isqrBOFg"
# Айди групп в которой он будет работать, белый список (массив из строк).
telegram_allowed_groups = ["-1001383474381"]
# Айди администраторов бота, белый список (массив из строк).
telegram_admin_ids = ["6261989159", "667588148"]

[openai]
openai_api_token = "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"
tokens_per_request_limit = 412
default_prompt_template = "Become a historical character (name given at the end). NEVER give direct information about yourself (name, parents, place and date of birth, etc.), only short answers that do not immediately reveal your identity are allowed. Answer only in that language you have been asked. Be concise, be direct. Do not mention the name of the company/organization or political party you belong to. Do not answer questions that you have not been asked. You should answer ONLY those questions that you are explicitly asked. Your job is to give an accurate and true representation of the character's thoughts, opinions, and experiences without directly revealing their identity. Use quotes and anecdotes from their life to substantiate your answers. Character : "

# Содержит хешкарту с ключем в виде даты и персонажем ввиде строки.
[calendar]
plan = [
    { date = "23-08-08", character = ["Sherlock Holms", "Шерлок Холмс", "Холмс Шерлок"] },
    { date = "23-08-09", character = ["Шерлок Холмс", "Холмс Шерлок"] },
    { date = "23-08-10", character = ["Клеопатра", "Cleopatra"] },
    { date = "23-08-11", character = ["Леонардо да Винчи", "Leonardo da Vinci"] },
    { date = "23-08-12", character = ["Мария Кюри", "Marie Curie"] },
    { date = "23-08-13", character = ["Альберт Эйнштейн", "Albert Einstein"] },
    { date = "23-08-14", character = ["Наполеон Бонапарт", "Napoleon Bonaparte"] },
    { date = "23-08-15", character = ["Вильям Шекспир", "William Shakespeare"] },
    { date = "23-08-16", character = ["Махатма Ганди", "Mahatma Gandhi"] },
    { date = "23-08-17", character = ["Александр Великий", "Alexander the Great"] },
    { date = "23-08-18", character = ["Елизавета I", "Elizabeth I"] },
    { date = "23-08-19", character = ["Александр Флеминг", "Alexander Fleming"] },
    { date = "23-08-20", character = ["Вольфганг Амадей Моцарт", "Wolfgang Amadeus Mozart"] },
    { date = "23-08-21", character = ["Чарльз Дарвин", "Charles Darwin"] },
    { date = "23-08-22", character = ["Джейн Остин", "Jane Austen"] },
    { date = "23-08-23", character = ["Мартин Лютер Кинг мл.", "Martin Luther King Jr."] },
    { date = "23-08-24", character = ["Анна Ахматова", "Anna Akhmatova"] },
]