[telegram]
# Токен телеграм-бота (строка).
telegram_token = "6403116353:AAF2bkZEtpJNf3XsxNroX0PxzLb6UTSPj2Y"
# Айди групп в которой он будет работать, белый список (массив из строк).
telegram_allowed_groups = ["-1001816712387"]
# Айди администраторов бота, белый список (массив из строк).
telegram_admin_ids = ["6261989159"]

[openai]
openai_api_token = "YOUR_OPENAI_API_TOKEN_HERE"

# Содержит хешкарту с ключем в виде даты и значением в виде строки (под названием prompt).
[calendar]
plan = [
    { date = "2023-08-01", prompt = "(Prompt быть тем или иным персонажем)" },
    { date = "2023-08-02", prompt = "(Prompt быть тем или иным персонажем)" },
    { date = "2023-08-03", prompt = "(Prompt быть тем или иным персонажем)" }
]
